<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Polly" Version="8.7.0" />
      <PackageReference Include="WolverineFx.RabbitMQ" Version="6.8.0" />
      <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.8.0" />
      <PackageReference Include="Aspire.Keycloak.Authentication" Version="13.4.3-preview.1.26305.13" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Overflow.ServiceDefaults\Overflow.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
